### ISSUE TITLE
users service request issue

### ISSUE THREAD

**Issue by viveki2it** [ostdotcom/ost-sdk-ruby#49]
Hi,

I have updated the ost sdk ruby and trying to use the release 2.0 (v2). I am able to connect ostsdk service. but, I am not able to use users service request. When I try the get_list or create, I am getting the below error.

2.5.1 :007 > response = users_service.get_list({})
 => {:success=>false, :err=>{:code=>"SOMETHING_WENT_WRONG", :internal_id=>"SDK(u_hh_2)", :msg=>"GET request Failed", :error_data=>[]}

Please help me on this. What would be or where would be wrong as I am doing. 

Regards,
Vivek.

**Comment by puneet-khushwani-eth** [comment]
Hi,

Can we please verify the value of 'api_base_url' param being passed in the constructor. 

Testnet Endpoint :  https://api.ost.com/testnet/v2/
Mainnet Endpoint : https://api.ost.com/mainnet/v2/

Regards,
Puneet

**Comment by viveki2it** [comment]
Hi Puneet,

I have tried with above both endpoints. But no luck. I am getting the same error.

Regards,
Vivek.

**Comment by puneet-khushwani-eth** [comment]
Hi Vivek,

Can you please share the following:

1. Ruby Version 
2. Complete Code snippet being used

Note: While sending the snippet to instantiate OSTSdk::Saas::Services , do not send the value of api_secret

Also sending a sample code for your reference: 

ost_sdk = OSTSdk::Saas::Services.new({
api_key: '6a59a63ba7c93f66e8bb6a55165a476a',
api_secret: <API_SECRET>,
api_base_url: 'https://api.ost.com/testnet/v2/',
config: {timeout: 60}
})

users_service = ost_sdk.services.users

response = users_service.get_list(get_params)

Thanks,
Puneet

**Comment by viveki2it** [comment]
Hi Puneet,

Please check below steps.

1) Ruby version - 2.5.1
2) I am following the below steps in the rails console. 
1) 2.5.1 :011 > api_key = <API_Key>
2) 2.5.1 :012 > api_secret = <api_secret>
3) 2.5.1 :013 > ost_sdk = OSTSdk::Saas::Services.new({api_key: api_key, api_secret: api_secret, api_base_url: api_base_url, config: {timeout: 60}})
4) 2.5.1 :014 > users_service = ost_sdk.services.users
5) 2.5.1 :015 > response = users_service.get_list({})
 => {:success=>false, :err=>{:code=>"SOMETHING_WENT_WRONG", :internal_id=>"SDK(u_hh_2)", :msg=>"GET request Failed", :error_data=>[]}}
6) 2.5.1 :016 > response = users_service.create({})
 => {:success=>false, :err=>{:code=>"SOMETHING_WENT_WRONG", :internal_id=>"SDK(u_hh_1)", :msg=>"POST request failed", :error_data=>[]}}

Regards,
Vivek.

**Comment by puneet-khushwani-eth** [comment]
Hi,

1. Please share API_KEY 

2. We added few logs for debugging the error in this case and published a beta version. Please install it by using 

gem install ost-sdk-ruby -v 2.0.1.beta1

With this version, could you please retry and share the logs with us. 

Thanks,
Puneet

**Comment by viveki2it** [comment]
Hi Puneet,

1. Api_key = df233130347314e7f4ceb5c0c93df7a8
2. 2.5.1 :007 > response = users_service.get_list({})
StandardError::message bad URI(is not URI?):  https://api.ost.com/testnet/v2/users/?api_key=df233130347314e7f4ceb5c0c93df7a8&api_request_timestamp=1554289448&api_signature_kind=OST1-HMAC-SHA256&api_signature=<signature>
StandardError::backtrace ["/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/common.rb:237:in `parse'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/uri/common.rb:743:in `URI'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/ost-sdk-ruby-2.0.1.beta1/lib/ost-sdk-ruby/util/http_helper.rb:71:in `block in send_get_request'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/ost-sdk-ruby-2.0.1.beta1/lib/ost-sdk-ruby/util/http_helper.rb:170:in `perform_and_handle_exceptions'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/ost-sdk-ruby-2.0.1.beta1/lib/ost-sdk-ruby/util/http_helper.rb:68:in `send_get_request'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/ost-sdk-ruby-2.0.1.beta1/lib/ost-sdk-ruby/saas/users.rb:36:in `get_list'", "(irb):7:in `irb_binding'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/workspace.rb:85:in `eval'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/workspace.rb:85:in `evaluate'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/context.rb:380:in `evaluate'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:491:in `block (2 levels) in eval_input'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:623:in `signal_status'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:488:in `block in eval_input'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `loop'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `catch'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `each_top_level_statement'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:487:in `eval_input'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:428:in `block in run'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:427:in `catch'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:427:in `run'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/irb.rb:383:in `start'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/railties-5.2.1/lib/rails/commands/console/console_command.rb:64:in `start'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/railties-5.2.1/lib/rails/commands/console/console_command.rb:19:in `start'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/railties-5.2.1/lib/rails/commands/console/console_command.rb:96:in `perform'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<main>'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'", "/home/vivekananda/work_orders/ostformservices/ostformservice/bin/rails:9:in `<main>'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'", "/home/vivekananda/.rvm/gems/ruby-2.5.1@ostformservice/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'", "/home/vivekananda/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'", "-e:1:in `<main>'"]
 => {:success=>false, :err=>{:code=>"SOMETHING_WENT_WRONG", :internal_id=>"SDK(u_hh_2)", :msg=>"GET request Failed", :error_data=>[]}} 

Regards,
Vivek

**Comment by puneet-khushwani-eth** [comment]
Hi Vivek,

As per the logs it looks like URI version being used in your case is not able to parse https://api.ost.com/testnet/v2/users/?api_key=df233130347314e7f4ceb5c0c93df7a8&api_request_timestamp=1554289448&api_signature_kind=OST1-HMAC-SHA256&api_signature=

This is unlike what we are seeing in version of URI available to us. Below are a few reasons known to us for which URI parsing would fail.

1. api_base_url being used in the code starts with a space.
2. api_key / api_secret / api_base_url has any special character. 

Can you please check if either of these cases exist. 

In the URL we see in the log sent, **api_signature** is empty. We are assuming that it would have been manually removed before sending them over. Please let us know if that's not the case. 

If problem still persists, would request you to login on https://help.ost.com/ and file a support ticket by sending us the complete ruby code snippet being used. Also as **api_signature** is encrypted, it would be safe for you to be sending it over to us in the support ticket you would create. 


Thanks,
Puneet

**Comment by viveki2it** [comment]
Hi Puneet,

Got it. Thanks for your help with the issues. 

Regards,
Vivek!
